import type { Industry, CustomField } from '@/types'

export interface SuggestedItem {
  name: string
  unit: string
  category: 'materia_prima' | 'insumo' | 'material_empaque' | 'producto_terminado'
  min_stock: number
}

export interface IndustryMeta {
  label: string
  region: string
  inputLabel: string
  outputLabel: string
  productExamples: string[]
  productionStages: string[]
  productionFields: CustomField[]
  regulator: string        // Ente regulador principal
  defaultConfig: {
    input_label: string
    output_label: string
    product_types: string[]
    stages: string[]
    custom_fields: CustomField[]
  }
  suggestedInventory: SuggestedItem[]
}

export const INDUSTRIES: Record<Industry, IndustryMeta> = {

  // ─── TAMBO ────────────────────────────────────────────────────────────────
  tambo: {
    label: 'Tambo / Producción lechera',
    region: 'Buenos Aires · Santa Fe · Córdoba · Entre Ríos',
    inputLabel: 'Vacas en ordeñe',
    outputLabel: 'Litros producidos',
    productExamples: ['Leche cruda entera', 'Leche descremada'],
    regulator: 'SENASA + CAA',
    productionStages: ['Ordeñe', 'Control de calidad', 'Enfriado', 'Entrega'],
    productionFields: [
      { key: 'vacas_ordeñe',    label: 'Vacas en ordeñe',              type: 'number', unit: 'cab.',     stage: 'Ordeñe' },
      { key: 'litros_totales',  label: 'Litros totales',               type: 'number', unit: 'L',        stage: 'Ordeñe' },
      { key: 'litros_vaca',     label: 'Litros por vaca',              type: 'number', unit: 'L/vaca',   stage: 'Ordeñe',            compliance_ref: 'Referencia productiva' },
      { key: 'grasa',           label: 'Tenor graso',                  type: 'number', unit: '%',        stage: 'Control de calidad', min_value: 3.0, compliance_ref: 'CAA Art. 554' },
      { key: 'proteina',        label: 'Proteína',                     type: 'number', unit: '%',        stage: 'Control de calidad', min_value: 2.9, compliance_ref: 'CAA Art. 554' },
      { key: 'acidez',          label: 'Acidez titulable',             type: 'number', unit: '°D',       stage: 'Control de calidad', min_value: 14, max_value: 18, compliance_ref: 'CAA Art. 554' },
      { key: 'densidad',        label: 'Densidad',                     type: 'number', unit: 'g/mL',     stage: 'Control de calidad', min_value: 1.028, max_value: 1.034, compliance_ref: 'CAA Art. 554' },
      { key: 'ccs',             label: 'Células somáticas (CCS)',      type: 'number', unit: 'x1000/mL', stage: 'Control de calidad', max_value: 400, compliance_ref: 'CAA Art. 554 — SENASA' },
      { key: 'ufc',             label: 'Recuento bacteriano (UFC)',    type: 'number', unit: 'UFC/mL',   stage: 'Control de calidad', max_value: 100000, compliance_ref: 'CAA Art. 554' },
      { key: 'temp_enfriado',   label: 'Temperatura de enfriado',      type: 'number', unit: '°C',       stage: 'Enfriado',           max_value: 4, compliance_ref: 'CAA Art. 556' },
      { key: 'litros_entregados', label: 'Litros entregados',          type: 'number', unit: 'L',        stage: 'Entrega' },
      { key: 'destino',         label: 'Destino',                      type: 'text',                     stage: 'Entrega' },
    ],
    defaultConfig: {
      input_label: 'Vacas en ordeñe',
      output_label: 'Litros producidos',
      product_types: ['Leche cruda entera', 'Leche descremada'],
      stages: ['Ordeñe', 'Control de calidad', 'Enfriado', 'Entrega'],
      custom_fields: [
        { key: 'vacas_ordeñe',     label: 'Vacas en ordeñe',           type: 'number', unit: 'cab.',     stage: 'Ordeñe' },
        { key: 'litros_totales',   label: 'Litros totales',            type: 'number', unit: 'L',        stage: 'Ordeñe' },
        { key: 'litros_vaca',      label: 'Litros por vaca',           type: 'number', unit: 'L/vaca',   stage: 'Ordeñe',             compliance_ref: 'Referencia productiva' },
        { key: 'grasa',            label: 'Tenor graso',               type: 'number', unit: '%',        stage: 'Control de calidad', min_value: 3.0,   compliance_ref: 'CAA Art. 554' },
        { key: 'proteina',         label: 'Proteína',                  type: 'number', unit: '%',        stage: 'Control de calidad', min_value: 2.9,   compliance_ref: 'CAA Art. 554' },
        { key: 'acidez',           label: 'Acidez titulable',          type: 'number', unit: '°D',       stage: 'Control de calidad', min_value: 14, max_value: 18, compliance_ref: 'CAA Art. 554' },
        { key: 'densidad',         label: 'Densidad',                  type: 'number', unit: 'g/mL',     stage: 'Control de calidad', min_value: 1.028, max_value: 1.034, compliance_ref: 'CAA Art. 554' },
        { key: 'ccs',              label: 'Células somáticas (CCS)',   type: 'number', unit: 'x1000/mL', stage: 'Control de calidad', max_value: 400,   compliance_ref: 'CAA Art. 554 — SENASA' },
        { key: 'ufc',              label: 'Recuento bacteriano (UFC)', type: 'number', unit: 'UFC/mL',   stage: 'Control de calidad', max_value: 100000,compliance_ref: 'CAA Art. 554' },
        { key: 'temp_enfriado',    label: 'Temperatura de enfriado',   type: 'number', unit: '°C',       stage: 'Enfriado',           max_value: 4,     compliance_ref: 'CAA Art. 556' },
        { key: 'litros_entregados',label: 'Litros entregados',         type: 'number', unit: 'L',        stage: 'Entrega' },
        { key: 'destino',          label: 'Destino',                   type: 'text',                     stage: 'Entrega' },
      ],
    },
    suggestedInventory: [
      { name: 'Pezoneras',               unit: 'unidad', category: 'insumo',        min_stock: 20 },
      { name: 'Sellador de pezones',     unit: 'L',      category: 'insumo',        min_stock: 10 },
      { name: 'Detergente alcalino',     unit: 'kg',     category: 'insumo',        min_stock: 20 },
      { name: 'Ácido cítrico',           unit: 'kg',     category: 'insumo',        min_stock: 10 },
      { name: 'Papel secado pezones',    unit: 'rollo',  category: 'insumo',        min_stock: 50 },
      { name: 'Tiras reactivas mastitis',unit: 'unidad', category: 'insumo',        min_stock: 100 },
    ],
  },

  // ─── DAIRY ────────────────────────────────────────────────────────────────
  dairy: {
    label: 'Lácteos / Elaboración de quesos',
    region: 'Todo el país',
    inputLabel: 'Litros de leche',
    outputLabel: 'Kg producidos',
    productExamples: ['Gouda', 'Sardo', 'Muzzarella', 'Cremoso', 'Yogur'],
    regulator: 'SENASA + CAA',
    productionStages: ['Recepción de leche', 'Pasteurización', 'Elaboración', 'Moldeado', 'Prensado', 'Salmuera', 'Maduración'],
    productionFields: [
      { key: 'temp_leche',             label: 'Temperatura leche',      type: 'number', unit: '°C',    stage: 'Recepción de leche', max_value: 10,                     compliance_ref: 'CAA Art. 556' },
      { key: 'acidez_recepcion',       label: 'Acidez titulable',       type: 'number', unit: '°D',    stage: 'Recepción de leche', min_value: 14,  max_value: 18,     compliance_ref: 'CAA Art. 554' },
      { key: 'densidad_leche',         label: 'Densidad',               type: 'number', unit: 'g/mL',  stage: 'Recepción de leche', min_value: 1.028, max_value: 1.034, compliance_ref: 'CAA Art. 554' },
      { key: 'temp_pasteurizacion',    label: 'Temperatura (HTST)',     type: 'number', unit: '°C',    stage: 'Pasteurización',     min_value: 72,                     compliance_ref: 'CAA Art. 560' },
      { key: 'tiempo_pasteurizacion',  label: 'Tiempo (HTST)',          type: 'number', unit: 'seg',   stage: 'Pasteurización',     min_value: 15,                     compliance_ref: 'CAA Art. 560' },
      { key: 'temp_cuba',              label: 'Temperatura de cuba',    type: 'number', unit: '°C',    stage: 'Elaboración',        min_value: 28,  max_value: 38 },
      { key: 'ph_inicial',             label: 'pH inicial',             type: 'number', unit: 'pH',    stage: 'Elaboración',        min_value: 6.5, max_value: 6.8 },
      { key: 'cuajo_ml',               label: 'Cuajo',                  type: 'number', unit: 'mL',    stage: 'Elaboración' },
      { key: 'fermento_g',             label: 'Fermento láctico',       type: 'number', unit: 'g',     stage: 'Elaboración' },
      { key: 'cloruro_calcio_g',       label: 'Cloruro de calcio',      type: 'number', unit: 'g',     stage: 'Elaboración' },
      { key: 'cantidad_moldes',        label: 'Cantidad de moldes',     type: 'number', unit: 'unid.', stage: 'Moldeado' },
      { key: 'peso_molde_kg',          label: 'Peso por molde',         type: 'number', unit: 'kg',    stage: 'Moldeado' },
      { key: 'tiempo_prensado_hs',     label: 'Tiempo de prensado',     type: 'number', unit: 'hs',    stage: 'Prensado' },
      { key: 'presion_bar',            label: 'Presión',                type: 'number', unit: 'bar',   stage: 'Prensado' },
      { key: 'tiempo_salmuera_hs',     label: 'Tiempo en salmuera',     type: 'number', unit: 'hs',    stage: 'Salmuera' },
      { key: 'concentracion_salmuera', label: 'Concentración',          type: 'number', unit: '%',     stage: 'Salmuera',           min_value: 18,  max_value: 22 },
      { key: 'temp_salmuera',          label: 'Temperatura salmuera',   type: 'number', unit: '°C',    stage: 'Salmuera',           min_value: 10,  max_value: 14 },
      { key: 'dias_maduracion',        label: 'Días de maduración',     type: 'number', unit: 'días',  stage: 'Maduración' },
      { key: 'temp_camara',            label: 'Temperatura cámara',     type: 'number', unit: '°C',    stage: 'Maduración',         min_value: 8,   max_value: 14, compliance_ref: 'SENASA Res. 47/2018' },
      { key: 'humedad_camara',         label: 'Humedad cámara',         type: 'number', unit: '%',     stage: 'Maduración',         min_value: 80,  max_value: 95 },
    ],
    defaultConfig: {
      input_label: 'Litros de leche',
      output_label: 'Kg de queso',
      product_types: ['Gouda', 'Sardo', 'Pategras', 'Cremoso', 'Muzzarella', 'Provoleta'],
      stages: ['Recepción de leche', 'Pasteurización', 'Elaboración', 'Moldeado', 'Prensado', 'Salmuera', 'Maduración'],
      custom_fields: [
        { key: 'temp_leche',             label: 'Temperatura leche',      type: 'number', unit: '°C',    stage: 'Recepción de leche', max_value: 10,                     compliance_ref: 'CAA Art. 556' },
        { key: 'acidez_recepcion',       label: 'Acidez titulable',       type: 'number', unit: '°D',    stage: 'Recepción de leche', min_value: 14,  max_value: 18,     compliance_ref: 'CAA Art. 554' },
        { key: 'densidad_leche',         label: 'Densidad',               type: 'number', unit: 'g/mL',  stage: 'Recepción de leche', min_value: 1.028, max_value: 1.034, compliance_ref: 'CAA Art. 554' },
        { key: 'temp_pasteurizacion',    label: 'Temperatura (HTST)',     type: 'number', unit: '°C',    stage: 'Pasteurización',     min_value: 72,                     compliance_ref: 'CAA Art. 560' },
        { key: 'tiempo_pasteurizacion',  label: 'Tiempo (HTST)',          type: 'number', unit: 'seg',   stage: 'Pasteurización',     min_value: 15,                     compliance_ref: 'CAA Art. 560' },
        { key: 'temp_cuba',              label: 'Temperatura de cuba',    type: 'number', unit: '°C',    stage: 'Elaboración',        min_value: 28,  max_value: 38 },
        { key: 'ph_inicial',             label: 'pH inicial',             type: 'number', unit: 'pH',    stage: 'Elaboración',        min_value: 6.5, max_value: 6.8 },
        { key: 'cuajo_ml',               label: 'Cuajo',                  type: 'number', unit: 'mL',    stage: 'Elaboración' },
        { key: 'fermento_g',             label: 'Fermento láctico',       type: 'number', unit: 'g',     stage: 'Elaboración' },
        { key: 'cloruro_calcio_g',       label: 'Cloruro de calcio',      type: 'number', unit: 'g',     stage: 'Elaboración' },
        { key: 'cantidad_moldes',        label: 'Cantidad de moldes',     type: 'number', unit: 'unid.', stage: 'Moldeado' },
        { key: 'peso_molde_kg',          label: 'Peso por molde',         type: 'number', unit: 'kg',    stage: 'Moldeado' },
        { key: 'tiempo_prensado_hs',     label: 'Tiempo de prensado',     type: 'number', unit: 'hs',    stage: 'Prensado' },
        { key: 'presion_bar',            label: 'Presión',                type: 'number', unit: 'bar',   stage: 'Prensado' },
        { key: 'tiempo_salmuera_hs',     label: 'Tiempo en salmuera',     type: 'number', unit: 'hs',    stage: 'Salmuera' },
        { key: 'concentracion_salmuera', label: 'Concentración',          type: 'number', unit: '%',     stage: 'Salmuera',           min_value: 18,  max_value: 22 },
        { key: 'temp_salmuera',          label: 'Temperatura salmuera',   type: 'number', unit: '°C',    stage: 'Salmuera',           min_value: 10,  max_value: 14 },
        { key: 'dias_maduracion',        label: 'Días de maduración',     type: 'number', unit: 'días',  stage: 'Maduración' },
        { key: 'temp_camara',            label: 'Temperatura cámara',     type: 'number', unit: '°C',    stage: 'Maduración',         min_value: 8,   max_value: 14, compliance_ref: 'SENASA Res. 47/2018' },
        { key: 'humedad_camara',         label: 'Humedad cámara',         type: 'number', unit: '%',     stage: 'Maduración',         min_value: 80,  max_value: 95 },
      ],
    },
    suggestedInventory: [
      { name: 'Sal', unit: 'kg', category: 'insumo', min_stock: 50 },
      { name: 'Cuajo', unit: 'L', category: 'insumo', min_stock: 2 },
      { name: 'Fermento láctico', unit: 'sobre', category: 'insumo', min_stock: 10 },
      { name: 'Cloruro de calcio', unit: 'kg', category: 'insumo', min_stock: 5 },
      { name: 'Envases plásticos', unit: 'unidad', category: 'material_empaque', min_stock: 200 },
      { name: 'Film stretch', unit: 'rollo', category: 'material_empaque', min_stock: 5 },
      { name: 'Etiquetas', unit: 'unidad', category: 'material_empaque', min_stock: 500 },
    ],
  },

  // ─── GANADERÍA ────────────────────────────────────────────────────────────
  ganaderia: {
    label: 'Ganadería',
    region: 'Pampa, NEA, Patagonia',
    inputLabel: 'Kg de forraje / ha',
    outputLabel: 'Kg de carne producidos',
    productExamples: ['Novillos', 'Vaquillonas', 'Terneros'],
    regulator: 'SENASA',
    productionStages: ['Recría', 'Engorde', 'Terminación', 'Venta'],
    productionFields: [
      { key: 'cabezas',       label: 'Cantidad de cabezas',           type: 'number', unit: 'cab.',    stage: 'Recría' },
      { key: 'potrero',       label: 'Potrero / lote',                type: 'text',                    stage: 'Recría' },
      { key: 'peso_promedio', label: 'Peso promedio',                 type: 'number', unit: 'kg',      stage: 'Engorde', min_value: 180, max_value: 550 },
      { key: 'gdp',           label: 'Ganancia diaria de peso (GDP)', type: 'number', unit: 'kg/día',  stage: 'Engorde', min_value: 0.4, max_value: 1.5, compliance_ref: 'SENASA — referencia productiva' },
      { key: 'peso_final',    label: 'Peso final promedio',           type: 'number', unit: 'kg',      stage: 'Terminación', min_value: 380, compliance_ref: 'SENASA Res. 57/1996 (peso mín. faena)' },
      { key: 'destino_venta', label: 'Destino de venta',              type: 'text',                    stage: 'Venta' },
    ],
    defaultConfig: {
      input_label: 'Kg de forraje',
      output_label: 'Kg de carne',
      product_types: ['Novillo', 'Vaquillona', 'Ternero', 'Toro'],
      stages: ['Recría', 'Engorde', 'Terminación', 'Venta'],
      custom_fields: [
        { key: 'cabezas',       label: 'Cantidad de cabezas',           type: 'number', unit: 'cab.',    stage: 'Recría' },
        { key: 'potrero',       label: 'Potrero / lote',                type: 'text',                    stage: 'Recría' },
        { key: 'peso_promedio', label: 'Peso promedio',                 type: 'number', unit: 'kg',      stage: 'Engorde', min_value: 180, max_value: 550 },
        { key: 'gdp',           label: 'Ganancia diaria de peso (GDP)', type: 'number', unit: 'kg/día',  stage: 'Engorde', min_value: 0.4, max_value: 1.5, compliance_ref: 'SENASA — referencia productiva' },
        { key: 'peso_final',    label: 'Peso final promedio',           type: 'number', unit: 'kg',      stage: 'Terminación', min_value: 380, compliance_ref: 'SENASA Res. 57/1996 (peso mín. faena)' },
        { key: 'destino_venta', label: 'Destino de venta',              type: 'text',                    stage: 'Venta' },
      ],
    },
    suggestedInventory: [
      { name: 'Alimento balanceado', unit: 'kg', category: 'insumo', min_stock: 1000 },
      { name: 'Sal mineral', unit: 'kg', category: 'insumo', min_stock: 100 },
      { name: 'Rollos de pasto', unit: 'unidad', category: 'materia_prima', min_stock: 20 },
      { name: 'Vacuna aftosa', unit: 'dosis', category: 'insumo', min_stock: 50 },
      { name: 'Antiparasitario', unit: 'L', category: 'insumo', min_stock: 5 },
      { name: 'Combustible', unit: 'L', category: 'insumo', min_stock: 200 },
    ],
  },

  // ─── FRIGORÍFICO ──────────────────────────────────────────────────────────
  frigorifico: {
    label: 'Frigorífico',
    region: 'Buenos Aires, Santa Fe, Entre Ríos',
    inputLabel: 'Cabezas faenadas',
    outputLabel: 'Kg de carne procesados',
    productExamples: ['Media res', 'Cuartos', 'Cortes especiales'],
    regulator: 'SENASA',
    productionStages: ['Recepción tropa', 'Faena', 'Oreo', 'Desposte', 'Despacho'],
    productionFields: [
      { key: 'cabezas_tropa',    label: 'Cabezas en tropa',       type: 'number', unit: 'cab.', stage: 'Recepción tropa' },
      { key: 'establecimiento',  label: 'Establecimiento origen', type: 'text',                 stage: 'Recepción tropa' },
      { key: 'rendimiento_res',  label: 'Rendimiento de res',     type: 'number', unit: '%',    stage: 'Faena', min_value: 45, max_value: 65, compliance_ref: 'SENASA Res. 4238' },
      { key: 'temp_camara',      label: 'Temp. cámara',           type: 'number', unit: '°C',   stage: 'Oreo',  min_value: 0,  max_value: 4,  compliance_ref: 'SENASA Res. 4238' },
      { key: 'horas_oreo',       label: 'Horas de oreo',          type: 'number', unit: 'hs',   stage: 'Oreo',  min_value: 24,                compliance_ref: 'SENASA Res. 4238' },
      { key: 'cortes_obtenidos', label: 'Cortes obtenidos',       type: 'text',                 stage: 'Desposte' },
      { key: 'destino',          label: 'Destino',                type: 'text',                 stage: 'Despacho' },
    ],
    defaultConfig: {
      input_label: 'Cabezas en tropa',
      output_label: 'Kg procesados',
      product_types: ['Media res bovina', 'Cuarto delantero', 'Cuarto trasero', 'Menudencias'],
      stages: ['Recepción tropa', 'Faena', 'Oreo', 'Desposte', 'Despacho'],
      custom_fields: [
        { key: 'cabezas_tropa',    label: 'Cabezas en tropa',       type: 'number', unit: 'cab.', stage: 'Recepción tropa' },
        { key: 'establecimiento',  label: 'Establecimiento origen', type: 'text',                 stage: 'Recepción tropa' },
        { key: 'rendimiento_res',  label: 'Rendimiento de res',     type: 'number', unit: '%',    stage: 'Faena', min_value: 45, max_value: 65, compliance_ref: 'SENASA Res. 4238' },
        { key: 'temp_camara',      label: 'Temp. cámara',           type: 'number', unit: '°C',   stage: 'Oreo',  min_value: 0,  max_value: 4,  compliance_ref: 'SENASA Res. 4238' },
        { key: 'horas_oreo',       label: 'Horas de oreo',          type: 'number', unit: 'hs',   stage: 'Oreo',  min_value: 24,                compliance_ref: 'SENASA Res. 4238' },
        { key: 'cortes_obtenidos', label: 'Cortes obtenidos',       type: 'text',                 stage: 'Desposte' },
        { key: 'destino',          label: 'Destino',                type: 'text',                 stage: 'Despacho' },
      ],
    },
    suggestedInventory: [
      { name: 'Sal gruesa', unit: 'kg', category: 'insumo', min_stock: 500 },
      { name: 'Hielo en escamas', unit: 'kg', category: 'insumo', min_stock: 200 },
      { name: 'Cajas de cartón', unit: 'unidad', category: 'material_empaque', min_stock: 300 },
      { name: 'Bolsas para cortes', unit: 'unidad', category: 'material_empaque', min_stock: 500 },
      { name: 'Film estirable', unit: 'rollo', category: 'material_empaque', min_stock: 10 },
      { name: 'Gas refrigerante', unit: 'kg', category: 'insumo', min_stock: 20 },
    ],
  },

  // ─── BODEGA ───────────────────────────────────────────────────────────────
  bodega: {
    label: 'Bodega / Vitivinicultura',
    region: 'Mendoza, San Juan, La Rioja, Río Negro',
    inputLabel: 'Kg de uva',
    outputLabel: 'Litros de vino',
    productExamples: ['Malbec', 'Cabernet', 'Torrontés', 'Chardonnay'],
    regulator: 'INV',
    productionStages: ['Recepción uva', 'Fermentación', 'Clarificación', 'Guarda', 'Embotellado'],
    productionFields: [
      { key: 'brix_inicial',       label: 'Densidad inicial',    type: 'number', unit: '°Brix', stage: 'Recepción uva',  min_value: 18,  max_value: 28,  compliance_ref: 'INV' },
      { key: 'anada',              label: 'Añada',               type: 'number',                stage: 'Recepción uva' },
      { key: 'temp_fermentacion',  label: 'Temp. fermentación',  type: 'number', unit: '°C',    stage: 'Fermentación',   min_value: 15,  max_value: 28,  compliance_ref: 'INV' },
      { key: 'brix_final',         label: 'Densidad final',      type: 'number', unit: '°Brix', stage: 'Fermentación',   max_value: 4 },
      { key: 'ph',                 label: 'pH',                  type: 'number', unit: 'pH',    stage: 'Clarificación',  min_value: 3.0, max_value: 3.8, compliance_ref: 'INV' },
      { key: 'so2_libre',          label: 'SO₂ libre',           type: 'number', unit: 'mg/L',  stage: 'Guarda',         max_value: 200,                 compliance_ref: 'INV Res. C.35/06' },
      { key: 'meses_guarda',       label: 'Meses de guarda',     type: 'number', unit: 'meses', stage: 'Guarda' },
      { key: 'botellas_obtenidas', label: 'Botellas obtenidas',  type: 'number', unit: 'unid.', stage: 'Embotellado' },
    ],
    defaultConfig: {
      input_label: 'Kg de uva',
      output_label: 'Litros de vino',
      product_types: ['Malbec', 'Cabernet Sauvignon', 'Torrontés', 'Chardonnay', 'Merlot', 'Blend'],
      stages: ['Recepción uva', 'Fermentación', 'Clarificación', 'Guarda', 'Embotellado'],
      custom_fields: [
        { key: 'brix_inicial',       label: 'Densidad inicial',    type: 'number', unit: '°Brix', stage: 'Recepción uva',  min_value: 18,  max_value: 28,  compliance_ref: 'INV' },
        { key: 'anada',              label: 'Añada',               type: 'number',                stage: 'Recepción uva' },
        { key: 'temp_fermentacion',  label: 'Temp. fermentación',  type: 'number', unit: '°C',    stage: 'Fermentación',   min_value: 15,  max_value: 28,  compliance_ref: 'INV' },
        { key: 'brix_final',         label: 'Densidad final',      type: 'number', unit: '°Brix', stage: 'Fermentación',   max_value: 4 },
        { key: 'ph',                 label: 'pH',                  type: 'number', unit: 'pH',    stage: 'Clarificación',  min_value: 3.0, max_value: 3.8, compliance_ref: 'INV' },
        { key: 'so2_libre',          label: 'SO₂ libre',           type: 'number', unit: 'mg/L',  stage: 'Guarda',         max_value: 200,                 compliance_ref: 'INV Res. C.35/06' },
        { key: 'meses_guarda',       label: 'Meses de guarda',     type: 'number', unit: 'meses', stage: 'Guarda' },
        { key: 'botellas_obtenidas', label: 'Botellas obtenidas',  type: 'number', unit: 'unid.', stage: 'Embotellado' },
      ],
    },
    suggestedInventory: [
      { name: 'Levadura enológica', unit: 'kg', category: 'insumo', min_stock: 2 },
      { name: 'Sulfito de potasio', unit: 'kg', category: 'insumo', min_stock: 5 },
      { name: 'Bentonita', unit: 'kg', category: 'insumo', min_stock: 10 },
      { name: 'Botellas 750ml', unit: 'unidad', category: 'material_empaque', min_stock: 500 },
      { name: 'Corchos', unit: 'unidad', category: 'material_empaque', min_stock: 500 },
      { name: 'Cápsulas', unit: 'unidad', category: 'material_empaque', min_stock: 500 },
      { name: 'Etiquetas', unit: 'unidad', category: 'material_empaque', min_stock: 500 },
    ],
  },

  // ─── CERVECERÍA ───────────────────────────────────────────────────────────
  cerveceria: {
    label: 'Cervecería artesanal',
    region: 'Todo el país',
    inputLabel: 'Kg de malta',
    outputLabel: 'Litros de cerveza',
    productExamples: ['Rubia', 'Roja', 'Negra', 'IPA', 'Stout'],
    regulator: 'ANMAT + CAA',
    productionStages: ['Maceración', 'Cocción', 'Fermentación', 'Maduración', 'Envasado'],
    productionFields: [
      { key: 'temp_macerado',    label: 'Temperatura macerado',   type: 'number', unit: '°C',  stage: 'Maceración',   min_value: 62,  max_value: 78 },
      { key: 'tiempo_macerado',  label: 'Tiempo de macerado',     type: 'number', unit: 'min', stage: 'Maceración',   min_value: 45,  max_value: 90 },
      { key: 'og',               label: 'Densidad original (OG)', type: 'number',              stage: 'Cocción',      min_value: 1.030, max_value: 1.110 },
      { key: 'ibu',              label: 'Amargor (IBU)',          type: 'number', unit: 'IBU', stage: 'Cocción' },
      { key: 'temp_fermentacion', label: 'Temp. fermentación',    type: 'number', unit: '°C',  stage: 'Fermentación', min_value: 10,  max_value: 25,  compliance_ref: 'CAA Art. 1082' },
      { key: 'fg',               label: 'Densidad final (FG)',    type: 'number',              stage: 'Fermentación', min_value: 1.005, max_value: 1.025 },
      { key: 'abv',              label: 'Alcohol (ABV)',          type: 'number', unit: '%',   stage: 'Maduración',   min_value: 0.5, max_value: 12,  compliance_ref: 'CAA Art. 1082' },
      { key: 'dias_maduracion',  label: 'Días de maduración',     type: 'number', unit: 'd',   stage: 'Maduración' },
      { key: 'litros_envasados', label: 'Litros envasados',       type: 'number', unit: 'L',   stage: 'Envasado' },
    ],
    defaultConfig: {
      input_label: 'Kg de malta',
      output_label: 'Litros producidos',
      product_types: ['Rubia / Lager', 'Roja / Amber', 'IPA', 'Stout / Porter', 'Trigo', 'Sour'],
      stages: ['Maceración', 'Cocción', 'Fermentación', 'Maduración', 'Envasado'],
      custom_fields: [
        { key: 'temp_macerado',    label: 'Temperatura macerado',   type: 'number', unit: '°C',  stage: 'Maceración',   min_value: 62,  max_value: 78 },
        { key: 'tiempo_macerado',  label: 'Tiempo de macerado',     type: 'number', unit: 'min', stage: 'Maceración',   min_value: 45,  max_value: 90 },
        { key: 'og',               label: 'Densidad original (OG)', type: 'number',              stage: 'Cocción',      min_value: 1.030, max_value: 1.110 },
        { key: 'ibu',              label: 'Amargor (IBU)',          type: 'number', unit: 'IBU', stage: 'Cocción' },
        { key: 'temp_fermentacion', label: 'Temp. fermentación',    type: 'number', unit: '°C',  stage: 'Fermentación', min_value: 10,  max_value: 25,  compliance_ref: 'CAA Art. 1082' },
        { key: 'fg',               label: 'Densidad final (FG)',    type: 'number',              stage: 'Fermentación', min_value: 1.005, max_value: 1.025 },
        { key: 'abv',              label: 'Alcohol (ABV)',          type: 'number', unit: '%',   stage: 'Maduración',   min_value: 0.5, max_value: 12,  compliance_ref: 'CAA Art. 1082' },
        { key: 'dias_maduracion',  label: 'Días de maduración',     type: 'number', unit: 'd',   stage: 'Maduración' },
        { key: 'litros_envasados', label: 'Litros envasados',       type: 'number', unit: 'L',   stage: 'Envasado' },
      ],
    },
    suggestedInventory: [
      { name: 'Malta base', unit: 'kg', category: 'materia_prima', min_stock: 100 },
      { name: 'Lúpulo', unit: 'kg', category: 'insumo', min_stock: 5 },
      { name: 'Levadura cervecera', unit: 'sobre', category: 'insumo', min_stock: 10 },
      { name: 'Irish moss (clarificante)', unit: 'kg', category: 'insumo', min_stock: 1 },
      { name: 'Botellas 1L', unit: 'unidad', category: 'material_empaque', min_stock: 200 },
      { name: 'Tapas corona', unit: 'unidad', category: 'material_empaque', min_stock: 500 },
      { name: 'Etiquetas', unit: 'unidad', category: 'material_empaque', min_stock: 300 },
    ],
  },

  // ─── APICULTURA ───────────────────────────────────────────────────────────
  apicultura: {
    label: 'Apicultura',
    region: 'Buenos Aires, Entre Ríos, La Pampa',
    inputLabel: 'Colmenas activas',
    outputLabel: 'Kg de miel',
    productExamples: ['Miel unifloral', 'Miel multifloral', 'Polen', 'Propóleos'],
    regulator: 'SENASA + CAA',
    productionStages: ['Cosecha', 'Extracción', 'Decantación', 'Fraccionamiento'],
    productionFields: [
      { key: 'colmenas_cosechadas', label: 'Colmenas cosechadas', type: 'number', unit: 'unid.', stage: 'Cosecha' },
      { key: 'flora',               label: 'Flora predominante',  type: 'text',                  stage: 'Cosecha' },
      { key: 'rendimiento_colmena', label: 'Kg por colmena',      type: 'number', unit: 'kg',    stage: 'Extracción', min_value: 5, max_value: 40 },
      { key: 'humedad',             label: 'Humedad de la miel',  type: 'number', unit: '%',     stage: 'Extracción', max_value: 20, compliance_ref: 'CAA Art. 782' },
      { key: 'brix_miel',           label: 'Brix',                type: 'number', unit: '°Brix', stage: 'Decantación', min_value: 78, compliance_ref: 'CAA Art. 782' },
      { key: 'kg_fraccionados',     label: 'Kg fraccionados',     type: 'number', unit: 'kg',    stage: 'Fraccionamiento' },
    ],
    defaultConfig: {
      input_label: 'Colmenas cosechadas',
      output_label: 'Kg de miel',
      product_types: ['Miel unifloral', 'Miel multifloral', 'Polen', 'Propóleos', 'Cera'],
      stages: ['Cosecha', 'Extracción', 'Decantación', 'Fraccionamiento'],
      custom_fields: [
        { key: 'colmenas_cosechadas', label: 'Colmenas cosechadas', type: 'number', unit: 'unid.', stage: 'Cosecha' },
        { key: 'flora',               label: 'Flora predominante',  type: 'text',                  stage: 'Cosecha' },
        { key: 'rendimiento_colmena', label: 'Kg por colmena',      type: 'number', unit: 'kg',    stage: 'Extracción', min_value: 5, max_value: 40 },
        { key: 'humedad',             label: 'Humedad de la miel',  type: 'number', unit: '%',     stage: 'Extracción', max_value: 20, compliance_ref: 'CAA Art. 782' },
        { key: 'brix_miel',           label: 'Brix',                type: 'number', unit: '°Brix', stage: 'Decantación', min_value: 78, compliance_ref: 'CAA Art. 782' },
        { key: 'kg_fraccionados',     label: 'Kg fraccionados',     type: 'number', unit: 'kg',    stage: 'Fraccionamiento' },
      ],
    },
    suggestedInventory: [
      { name: 'Azúcar (alimentación)', unit: 'kg', category: 'insumo', min_stock: 100 },
      { name: 'Alzas melarias', unit: 'unidad', category: 'insumo', min_stock: 10 },
      { name: 'Marcos', unit: 'unidad', category: 'insumo', min_stock: 50 },
      { name: 'Cera estampada', unit: 'kg', category: 'insumo', min_stock: 5 },
      { name: 'Ácido oxálico (varroa)', unit: 'kg', category: 'insumo', min_stock: 2 },
      { name: 'Tambores 300kg', unit: 'unidad', category: 'material_empaque', min_stock: 5 },
      { name: 'Frascos fraccionados', unit: 'unidad', category: 'material_empaque', min_stock: 200 },
    ],
  },

  // ─── OLIVICULTURA ─────────────────────────────────────────────────────────
  olivicultura: {
    label: 'Olivicultura / Aceite de oliva',
    region: 'San Juan, Mendoza, La Rioja, Catamarca',
    inputLabel: 'Kg de aceituna',
    outputLabel: 'Litros de aceite',
    productExamples: ['Extra virgen', 'Virgen', 'Aceitunas en conserva'],
    regulator: 'SENASA + CAA',
    productionStages: ['Recepción aceituna', 'Molido', 'Centrifugado', 'Filtrado', 'Envasado'],
    productionFields: [
      { key: 'variedad',          label: 'Variedad',          type: 'text',                     stage: 'Recepción aceituna' },
      { key: 'indice_madurez',    label: 'Índice de madurez', type: 'number',                   stage: 'Recepción aceituna', min_value: 1, max_value: 5 },
      { key: 'temp_molino',       label: 'Temperatura',       type: 'number', unit: '°C',       stage: 'Molido',             max_value: 27, compliance_ref: 'CAA Art. 519 (extracción en frío)' },
      { key: 'rendimiento_graso', label: 'Rendimiento graso', type: 'number', unit: '%',        stage: 'Centrifugado',       min_value: 15, max_value: 25 },
      { key: 'acidez',            label: 'Acidez',            type: 'number', unit: '% oleico', stage: 'Filtrado',           max_value: 0.8, compliance_ref: 'CAA Art. 519 (extra virgen)' },
      { key: 'litros_envasados',  label: 'Litros envasados',  type: 'number', unit: 'L',        stage: 'Envasado' },
    ],
    defaultConfig: {
      input_label: 'Kg de aceituna',
      output_label: 'Litros de aceite',
      product_types: ['Aceite extra virgen', 'Aceite virgen', 'Aceitunas verdes', 'Aceitunas negras'],
      stages: ['Recepción aceituna', 'Molido', 'Centrifugado', 'Filtrado', 'Envasado'],
      custom_fields: [
        { key: 'variedad',          label: 'Variedad',          type: 'text',                     stage: 'Recepción aceituna' },
        { key: 'indice_madurez',    label: 'Índice de madurez', type: 'number',                   stage: 'Recepción aceituna', min_value: 1, max_value: 5 },
        { key: 'temp_molino',       label: 'Temperatura',       type: 'number', unit: '°C',       stage: 'Molido',             max_value: 27, compliance_ref: 'CAA Art. 519 (extracción en frío)' },
        { key: 'rendimiento_graso', label: 'Rendimiento graso', type: 'number', unit: '%',        stage: 'Centrifugado',       min_value: 15, max_value: 25 },
        { key: 'acidez',            label: 'Acidez',            type: 'number', unit: '% oleico', stage: 'Filtrado',           max_value: 0.8, compliance_ref: 'CAA Art. 519 (extra virgen)' },
        { key: 'litros_envasados',  label: 'Litros envasados',  type: 'number', unit: 'L',        stage: 'Envasado' },
      ],
    },
    suggestedInventory: [
      { name: 'Nitrógeno (inertización)', unit: 'kg', category: 'insumo', min_stock: 10 },
      { name: 'Botellas 500ml', unit: 'unidad', category: 'material_empaque', min_stock: 500 },
      { name: 'Botellas 250ml', unit: 'unidad', category: 'material_empaque', min_stock: 300 },
      { name: 'Tapas', unit: 'unidad', category: 'material_empaque', min_stock: 500 },
      { name: 'Etiquetas', unit: 'unidad', category: 'material_empaque', min_stock: 500 },
      { name: 'Bidones 5L', unit: 'unidad', category: 'material_empaque', min_stock: 50 },
    ],
  },

  // ─── CEREALERA ────────────────────────────────────────────────────────────
  cerealera: {
    label: 'Cerealera / Acopio',
    region: 'Córdoba, Santa Fe, Buenos Aires, Entre Ríos',
    inputLabel: 'Toneladas recibidas',
    outputLabel: 'Toneladas despachadas',
    productExamples: ['Soja', 'Maíz', 'Trigo', 'Girasol', 'Sorgo'],
    regulator: 'SENASA + ONCCA',
    productionStages: ['Recepción', 'Secado', 'Almacenado', 'Despacho'],
    productionFields: [
      { key: 'humedad_entrada', label: 'Humedad entrada',      type: 'number', unit: '%',     stage: 'Recepción',  max_value: 14.5, compliance_ref: 'SENASA / Norma comercial' },
      { key: 'ph_hecto',        label: 'Peso hectolítrico',    type: 'number', unit: 'kg/hl', stage: 'Recepción',  min_value: 74,   compliance_ref: 'Norma comercial trigo' },
      { key: 'humedad_salida',  label: 'Humedad post-secado',  type: 'number', unit: '%',     stage: 'Secado',     max_value: 14,   compliance_ref: 'SENASA / Norma comercial' },
      { key: 'temp_secado',     label: 'Temperatura secado',   type: 'number', unit: '°C',    stage: 'Secado',     max_value: 110,  compliance_ref: 'Referencia técnica' },
      { key: 'silo',            label: 'Silo / celda',         type: 'text',                  stage: 'Almacenado' },
      { key: 'destino',         label: 'Destino despacho',     type: 'text',                  stage: 'Despacho' },
    ],
    defaultConfig: {
      input_label: 'Toneladas recibidas',
      output_label: 'Toneladas despachadas',
      product_types: ['Soja', 'Maíz', 'Trigo', 'Girasol', 'Sorgo', 'Cebada'],
      stages: ['Recepción', 'Secado', 'Almacenado', 'Despacho'],
      custom_fields: [
        { key: 'humedad_entrada', label: 'Humedad entrada',     type: 'number', unit: '%',     stage: 'Recepción',  max_value: 14.5, compliance_ref: 'SENASA / Norma comercial' },
        { key: 'ph_hecto',        label: 'Peso hectolítrico',   type: 'number', unit: 'kg/hl', stage: 'Recepción',  min_value: 74,   compliance_ref: 'Norma comercial trigo' },
        { key: 'humedad_salida',  label: 'Humedad post-secado', type: 'number', unit: '%',     stage: 'Secado',     max_value: 14,   compliance_ref: 'SENASA / Norma comercial' },
        { key: 'temp_secado',     label: 'Temperatura secado',  type: 'number', unit: '°C',    stage: 'Secado',     max_value: 110,  compliance_ref: 'Referencia técnica' },
        { key: 'silo',            label: 'Silo / celda',        type: 'text',                  stage: 'Almacenado' },
        { key: 'destino',         label: 'Destino despacho',    type: 'text',                  stage: 'Despacho' },
      ],
    },
    suggestedInventory: [
      { name: 'Soja', unit: 'tn', category: 'materia_prima', min_stock: 50 },
      { name: 'Maíz', unit: 'tn', category: 'materia_prima', min_stock: 50 },
      { name: 'Trigo', unit: 'tn', category: 'materia_prima', min_stock: 50 },
      { name: 'Bolsas big bag', unit: 'unidad', category: 'material_empaque', min_stock: 20 },
      { name: 'Combustible gasoil', unit: 'L', category: 'insumo', min_stock: 500 },
      { name: 'Insecticida almacenaje', unit: 'L', category: 'insumo', min_stock: 10 },
    ],
  },

  // ─── AGRO CAMPO ───────────────────────────────────────────────────────────
  agro_campo: {
    label: 'Campo agrícola',
    region: 'Pampa húmeda, NOA',
    inputLabel: 'Hectáreas trabajadas',
    outputLabel: 'Toneladas cosechadas',
    productExamples: ['Soja', 'Maíz', 'Trigo', 'Girasol'],
    regulator: 'SENASA',
    productionStages: ['Siembra', 'Labores culturales', 'Cosecha', 'Comercialización'],
    productionFields: [
      { key: 'lote',          label: 'Lote / potrero',      type: 'text',                   stage: 'Siembra' },
      { key: 'has_sembradas', label: 'Hectáreas sembradas', type: 'number', unit: 'ha',     stage: 'Siembra' },
      { key: 'anio_campana',  label: 'Campaña',             type: 'text',                   stage: 'Siembra' },
      { key: 'precipitaciones', label: 'Precipitaciones',   type: 'number', unit: 'mm',     stage: 'Labores culturales' },
      { key: 'rinde_ha',      label: 'Rinde por ha',        type: 'number', unit: 'tn/ha',  stage: 'Cosecha' },
      { key: 'humedad',       label: 'Humedad cosecha',     type: 'number', unit: '%',      stage: 'Cosecha', max_value: 14, compliance_ref: 'Norma comercial' },
      { key: 'precio_tn',     label: 'Precio por tn',       type: 'number', unit: 'ARS',    stage: 'Comercialización' },
    ],
    defaultConfig: {
      input_label: 'Hectáreas sembradas',
      output_label: 'Toneladas cosechadas',
      product_types: ['Soja', 'Maíz', 'Trigo', 'Girasol', 'Sorgo'],
      stages: ['Siembra', 'Labores culturales', 'Cosecha', 'Comercialización'],
      custom_fields: [
        { key: 'lote',          label: 'Lote / potrero',       type: 'text',                   stage: 'Siembra' },
        { key: 'has_sembradas', label: 'Hectáreas sembradas',  type: 'number', unit: 'ha',     stage: 'Siembra' },
        { key: 'anio_campana',  label: 'Campaña',              type: 'text',                   stage: 'Siembra' },
        { key: 'precipitaciones', label: 'Precipitaciones',    type: 'number', unit: 'mm',     stage: 'Labores culturales' },
        { key: 'rinde_ha',      label: 'Rinde por ha',         type: 'number', unit: 'tn/ha',  stage: 'Cosecha' },
        { key: 'humedad',       label: 'Humedad cosecha',      type: 'number', unit: '%',      stage: 'Cosecha', max_value: 14, compliance_ref: 'Norma comercial' },
        { key: 'precio_tn',     label: 'Precio por tn',        type: 'number', unit: 'ARS',    stage: 'Comercialización' },
      ],
    },
    suggestedInventory: [
      { name: 'Semillas de soja', unit: 'kg', category: 'materia_prima', min_stock: 500 },
      { name: 'Herbicida glifosato', unit: 'L', category: 'insumo', min_stock: 100 },
      { name: 'Fertilizante urea', unit: 'kg', category: 'insumo', min_stock: 1000 },
      { name: 'Insecticida', unit: 'L', category: 'insumo', min_stock: 20 },
      { name: 'Combustible gasoil', unit: 'L', category: 'insumo', min_stock: 1000 },
      { name: 'Aceite motor', unit: 'L', category: 'insumo', min_stock: 20 },
    ],
  },

  // ─── AVICULTURA ───────────────────────────────────────────────────────────
  avicultura: {
    label: 'Avicultura',
    region: 'Entre Ríos, Buenos Aires, Santa Fe',
    inputLabel: 'Kg de alimento',
    outputLabel: 'Kg de pollo / docenas huevo',
    productExamples: ['Pollo entero', 'Trozado', 'Huevo docena'],
    regulator: 'SENASA',
    productionStages: ['Recría', 'Engorde', 'Faena', 'Procesado'],
    productionFields: [
      { key: 'cantidad_aves',   label: 'Cantidad de aves',       type: 'number', unit: 'aves', stage: 'Recría' },
      { key: 'mortalidad',      label: 'Mortalidad',             type: 'number', unit: '%',    stage: 'Recría',    max_value: 5, compliance_ref: 'SENASA — referencia productiva' },
      { key: 'peso_promedio',   label: 'Peso promedio',          type: 'number', unit: 'kg',   stage: 'Engorde',   min_value: 0.5, max_value: 4 },
      { key: 'conversion',      label: 'Conversión alimenticia', type: 'number',               stage: 'Engorde',   min_value: 1.5, max_value: 2.2, compliance_ref: 'Referencia productiva' },
      { key: 'rendimiento_res', label: 'Rendimiento de res',     type: 'number', unit: '%',    stage: 'Faena',     min_value: 70, compliance_ref: 'SENASA' },
      { key: 'kg_procesados',   label: 'Kg procesados',          type: 'number', unit: 'kg',   stage: 'Procesado' },
    ],
    defaultConfig: {
      input_label: 'Kg de alimento balanceado',
      output_label: 'Kg producidos',
      product_types: ['Pollo entero', 'Pollo trozado', 'Huevo categoría A', 'Huevo categoría B'],
      stages: ['Recría', 'Engorde', 'Faena', 'Procesado'],
      custom_fields: [
        { key: 'cantidad_aves',   label: 'Cantidad de aves',       type: 'number', unit: 'aves', stage: 'Recría' },
        { key: 'mortalidad',      label: 'Mortalidad',             type: 'number', unit: '%',    stage: 'Recría',    max_value: 5, compliance_ref: 'SENASA — referencia productiva' },
        { key: 'peso_promedio',   label: 'Peso promedio',          type: 'number', unit: 'kg',   stage: 'Engorde',   min_value: 0.5, max_value: 4 },
        { key: 'conversion',      label: 'Conversión alimenticia', type: 'number',               stage: 'Engorde',   min_value: 1.5, max_value: 2.2, compliance_ref: 'Referencia productiva' },
        { key: 'rendimiento_res', label: 'Rendimiento de res',     type: 'number', unit: '%',    stage: 'Faena',     min_value: 70, compliance_ref: 'SENASA' },
        { key: 'kg_procesados',   label: 'Kg procesados',          type: 'number', unit: 'kg',   stage: 'Procesado' },
      ],
    },
    suggestedInventory: [
      { name: 'Alimento balanceado inicio', unit: 'kg', category: 'materia_prima', min_stock: 2000 },
      { name: 'Alimento balanceado engorde', unit: 'kg', category: 'materia_prima', min_stock: 2000 },
      { name: 'Vitaminas y minerales', unit: 'kg', category: 'insumo', min_stock: 10 },
      { name: 'Vacuna Marek', unit: 'dosis', category: 'insumo', min_stock: 100 },
      { name: 'Viruta / cama', unit: 'fardo', category: 'insumo', min_stock: 20 },
      { name: 'Bandejas para huevo', unit: 'unidad', category: 'material_empaque', min_stock: 200 },
    ],
  },

  // ─── CHACINADOS ───────────────────────────────────────────────────────────
  chacinados: {
    label: 'Chacinados / Embutidos',
    region: 'Santa Fe, Córdoba, La Pampa',
    inputLabel: 'Kg de carne',
    outputLabel: 'Kg de producto terminado',
    productExamples: ['Salame', 'Chorizo', 'Morcilla', 'Jamón'],
    regulator: 'SENASA + CAA',
    productionStages: ['Formulación', 'Embutido', 'Cocción / Ahumado', 'Maduración', 'Envasado'],
    productionFields: [
      { key: 'receta',           label: 'Receta / formulación',        type: 'text',               stage: 'Formulación' },
      { key: 'aditivos',         label: 'Aditivos usados',             type: 'text',               stage: 'Formulación' },
      { key: 'metros_embutidos', label: 'Metros embutidos',            type: 'number', unit: 'm',  stage: 'Embutido' },
      { key: 'temp_coccion',     label: 'Temperatura interna cocción', type: 'number', unit: '°C', stage: 'Cocción / Ahumado', min_value: 72, compliance_ref: 'CAA Art. 302' },
      { key: 'horas_coccion',    label: 'Horas de cocción / ahumado',  type: 'number', unit: 'hs', stage: 'Cocción / Ahumado' },
      { key: 'temp_camara',      label: 'Temp. cámara maduración',     type: 'number', unit: '°C', stage: 'Maduración', min_value: 0, max_value: 4, compliance_ref: 'SENASA' },
      { key: 'humedad_rel',      label: 'Humedad relativa',            type: 'number', unit: '%',  stage: 'Maduración', min_value: 75, max_value: 85 },
      { key: 'dias_maduracion',  label: 'Días de maduración',          type: 'number', unit: 'd',  stage: 'Maduración' },
      { key: 'kg_envasados',     label: 'Kg envasados',                type: 'number', unit: 'kg', stage: 'Envasado' },
    ],
    defaultConfig: {
      input_label: 'Kg de carne',
      output_label: 'Kg de chacinado',
      product_types: ['Salame', 'Chorizo seco', 'Chorizo fresco', 'Morcilla', 'Jamón cocido', 'Bondiola'],
      stages: ['Formulación', 'Embutido', 'Cocción / Ahumado', 'Maduración', 'Envasado'],
      custom_fields: [
        { key: 'receta',           label: 'Receta / formulación',        type: 'text',               stage: 'Formulación' },
        { key: 'aditivos',         label: 'Aditivos usados',             type: 'text',               stage: 'Formulación' },
        { key: 'metros_embutidos', label: 'Metros embutidos',            type: 'number', unit: 'm',  stage: 'Embutido' },
        { key: 'temp_coccion',     label: 'Temperatura interna cocción', type: 'number', unit: '°C', stage: 'Cocción / Ahumado', min_value: 72, compliance_ref: 'CAA Art. 302' },
        { key: 'horas_coccion',    label: 'Horas de cocción / ahumado',  type: 'number', unit: 'hs', stage: 'Cocción / Ahumado' },
        { key: 'temp_camara',      label: 'Temp. cámara maduración',     type: 'number', unit: '°C', stage: 'Maduración', min_value: 0, max_value: 4, compliance_ref: 'SENASA' },
        { key: 'humedad_rel',      label: 'Humedad relativa',            type: 'number', unit: '%',  stage: 'Maduración', min_value: 75, max_value: 85 },
        { key: 'dias_maduracion',  label: 'Días de maduración',          type: 'number', unit: 'd',  stage: 'Maduración' },
        { key: 'kg_envasados',     label: 'Kg envasados',                type: 'number', unit: 'kg', stage: 'Envasado' },
      ],
    },
    suggestedInventory: [
      { name: 'Sal fina', unit: 'kg', category: 'insumo', min_stock: 50 },
      { name: 'Pimienta negra', unit: 'kg', category: 'insumo', min_stock: 5 },
      { name: 'Ajo en polvo', unit: 'kg', category: 'insumo', min_stock: 5 },
      { name: 'Tripa natural', unit: 'metro', category: 'insumo', min_stock: 100 },
      { name: 'Tripa sintética', unit: 'metro', category: 'insumo', min_stock: 100 },
      { name: 'Bolsas al vacío', unit: 'unidad', category: 'material_empaque', min_stock: 300 },
      { name: 'Etiquetas', unit: 'unidad', category: 'material_empaque', min_stock: 500 },
    ],
  },

  // ─── YERBATERA ────────────────────────────────────────────────────────────
  yerbatera: {
    label: 'Yerba mate / Té',
    region: 'Misiones, Corrientes',
    inputLabel: 'Kg de hoja verde',
    outputLabel: 'Kg de yerba/té procesado',
    productExamples: ['Yerba mate', 'Té negro', 'Té verde'],
    regulator: 'INYM + SENASA',
    productionStages: ['Sapecado', 'Secado', 'Canchado', 'Estacionamiento', 'Molienda'],
    productionFields: [
      { key: 'temp_sapecado',   label: 'Temperatura sapecado',     type: 'number', unit: '°C',    stage: 'Sapecado',        min_value: 280, max_value: 350, compliance_ref: 'Referencia técnica' },
      { key: 'humedad_entrada', label: 'Humedad hoja entrada',     type: 'number', unit: '%',     stage: 'Sapecado',        min_value: 65,  max_value: 80 },
      { key: 'temp_secado',     label: 'Temperatura secado',       type: 'number', unit: '°C',    stage: 'Secado',          max_value: 120, compliance_ref: 'Referencia técnica' },
      { key: 'humedad_final',   label: 'Humedad final',            type: 'number', unit: '%',     stage: 'Secado',          max_value: 10,  compliance_ref: 'INYM Res. 1/2002' },
      { key: 'rendimiento',     label: 'Rendimiento seco',         type: 'number', unit: '%',     stage: 'Canchado',        min_value: 35,  max_value: 55 },
      { key: 'meses_estacion',  label: 'Meses de estacionamiento', type: 'number', unit: 'meses', stage: 'Estacionamiento', min_value: 9,   compliance_ref: 'INYM — mínimo legal' },
      { key: 'granulometria',   label: 'Granulometría',            type: 'text',                  stage: 'Molienda' },
    ],
    defaultConfig: {
      input_label: 'Kg de hoja verde',
      output_label: 'Kg de producto seco',
      product_types: ['Yerba mate elaborada', 'Té negro', 'Té verde', 'Té blanco'],
      stages: ['Sapecado', 'Secado', 'Canchado', 'Estacionamiento', 'Molienda'],
      custom_fields: [
        { key: 'temp_sapecado',   label: 'Temperatura sapecado',     type: 'number', unit: '°C',    stage: 'Sapecado',        min_value: 280, max_value: 350, compliance_ref: 'Referencia técnica' },
        { key: 'humedad_entrada', label: 'Humedad hoja entrada',     type: 'number', unit: '%',     stage: 'Sapecado',        min_value: 65,  max_value: 80 },
        { key: 'temp_secado',     label: 'Temperatura secado',       type: 'number', unit: '°C',    stage: 'Secado',          max_value: 120, compliance_ref: 'Referencia técnica' },
        { key: 'humedad_final',   label: 'Humedad final',            type: 'number', unit: '%',     stage: 'Secado',          max_value: 10,  compliance_ref: 'INYM Res. 1/2002' },
        { key: 'rendimiento',     label: 'Rendimiento seco',         type: 'number', unit: '%',     stage: 'Canchado',        min_value: 35,  max_value: 55 },
        { key: 'meses_estacion',  label: 'Meses de estacionamiento', type: 'number', unit: 'meses', stage: 'Estacionamiento', min_value: 9,   compliance_ref: 'INYM — mínimo legal' },
        { key: 'granulometria',   label: 'Granulometría',            type: 'text',                  stage: 'Molienda' },
      ],
    },
    suggestedInventory: [
      { name: 'Hoja verde de yerba', unit: 'kg', category: 'materia_prima', min_stock: 1000 },
      { name: 'Bolsas kraft 500g', unit: 'unidad', category: 'material_empaque', min_stock: 500 },
      { name: 'Bolsas kraft 1kg', unit: 'unidad', category: 'material_empaque', min_stock: 500 },
      { name: 'Hilo sellador', unit: 'rollo', category: 'material_empaque', min_stock: 5 },
      { name: 'Etiquetas', unit: 'unidad', category: 'material_empaque', min_stock: 500 },
      { name: 'Combustible secadero', unit: 'L', category: 'insumo', min_stock: 200 },
    ],
  },

  // ─── FRUTICULTURA ─────────────────────────────────────────────────────────
  fruticultura: {
    label: 'Fruticultura / Citricultura',
    region: 'NOA, NEA, Patagonia',
    inputLabel: 'Kg de fruta cosechada',
    outputLabel: 'Kg empacados / litros de jugo',
    productExamples: ['Limón', 'Naranja', 'Manzana', 'Pera', 'Arándano'],
    regulator: 'SENASA',
    productionStages: ['Cosecha', 'Selección', 'Empaque', 'Cámara frío', 'Despacho'],
    productionFields: [
      { key: 'calibre',         label: 'Calibre promedio', type: 'text',                  stage: 'Cosecha' },
      { key: 'brix',            label: 'Brix (dulzor)',    type: 'number', unit: '°Brix', stage: 'Cosecha' },
      { key: 'merma',           label: 'Merma selección',  type: 'number', unit: '%',     stage: 'Selección',  max_value: 15 },
      { key: 'cajas_embaladas', label: 'Cajas embaladas',  type: 'number', unit: 'unid.', stage: 'Empaque' },
      { key: 'destino',         label: 'Destino',          type: 'select', options: ['Mercado interno', 'Exportación', 'Industria'], stage: 'Empaque' },
      { key: 'temp_camara',     label: 'Temp. cámara',     type: 'number', unit: '°C',    stage: 'Cámara frío', min_value: 0, max_value: 4, compliance_ref: 'SENASA' },
      { key: 'dias_camara',     label: 'Días en cámara',   type: 'number', unit: 'd',     stage: 'Cámara frío' },
      { key: 'transportista',   label: 'Transportista',    type: 'text',                  stage: 'Despacho' },
    ],
    defaultConfig: {
      input_label: 'Kg de fruta cosechada',
      output_label: 'Kg empacados',
      product_types: ['Limón', 'Naranja', 'Mandarina', 'Manzana', 'Pera', 'Arándano'],
      stages: ['Cosecha', 'Selección', 'Empaque', 'Cámara frío', 'Despacho'],
      custom_fields: [
        { key: 'calibre',         label: 'Calibre promedio', type: 'text',                  stage: 'Cosecha' },
        { key: 'brix',            label: 'Brix (dulzor)',    type: 'number', unit: '°Brix', stage: 'Cosecha' },
        { key: 'merma',           label: 'Merma selección',  type: 'number', unit: '%',     stage: 'Selección',  max_value: 15 },
        { key: 'cajas_embaladas', label: 'Cajas embaladas',  type: 'number', unit: 'unid.', stage: 'Empaque' },
        { key: 'destino',         label: 'Destino',          type: 'select', options: ['Mercado interno', 'Exportación', 'Industria'], stage: 'Empaque' },
        { key: 'temp_camara',     label: 'Temp. cámara',     type: 'number', unit: '°C',    stage: 'Cámara frío', min_value: 0, max_value: 4, compliance_ref: 'SENASA' },
        { key: 'dias_camara',     label: 'Días en cámara',   type: 'number', unit: 'd',     stage: 'Cámara frío' },
        { key: 'transportista',   label: 'Transportista',    type: 'text',                  stage: 'Despacho' },
      ],
    },
    suggestedInventory: [
      { name: 'Cajas de cartón', unit: 'unidad', category: 'material_empaque', min_stock: 500 },
      { name: 'Bolsas de malla', unit: 'unidad', category: 'material_empaque', min_stock: 300 },
      { name: 'Etiquetas', unit: 'unidad', category: 'material_empaque', min_stock: 1000 },
      { name: 'Cera para fruta', unit: 'kg', category: 'insumo', min_stock: 10 },
      { name: 'Fungicida postcosecha', unit: 'L', category: 'insumo', min_stock: 5 },
      { name: 'Pallets', unit: 'unidad', category: 'material_empaque', min_stock: 20 },
    ],
  },

  // ─── HIDROPONÍA ───────────────────────────────────────────────────────────
  hidroponia: {
    label: 'Hidroponía',
    region: 'Todo el país',
    inputLabel: 'Solución nutritiva (L)',
    outputLabel: 'Kg de producto cosechado',
    productExamples: ['Lechuga', 'Tomate', 'Albahaca', 'Espinaca'],
    regulator: 'SENASA',
    productionStages: ['Siembra', 'Trasplante', 'Crecimiento', 'Cosecha'],
    productionFields: [
      { key: 'cantidad_plantas', label: 'Cantidad de plantas',     type: 'number', unit: 'unid.',  stage: 'Siembra' },
      { key: 'ph_solucion',      label: 'pH solución',             type: 'number', unit: 'pH',     stage: 'Trasplante',  min_value: 5.5, max_value: 6.5, compliance_ref: 'Referencia técnica' },
      { key: 'ce',               label: 'Conductividad eléctrica', type: 'number', unit: 'mS/cm',  stage: 'Crecimiento', min_value: 1.5, max_value: 3.5, compliance_ref: 'Referencia técnica' },
      { key: 'temp_agua',        label: 'Temperatura del agua',    type: 'number', unit: '°C',     stage: 'Crecimiento', min_value: 18,  max_value: 24,  compliance_ref: 'Referencia técnica' },
      { key: 'dias_ciclo',       label: 'Días del ciclo',          type: 'number', unit: 'd',      stage: 'Cosecha' },
      { key: 'kg_cosechados',    label: 'Kg cosechados',           type: 'number', unit: 'kg',     stage: 'Cosecha' },
    ],
    defaultConfig: {
      input_label: 'Litros de solución nutritiva',
      output_label: 'Kg cosechados',
      product_types: ['Lechuga', 'Rúcula', 'Tomate cherry', 'Albahaca', 'Espinaca', 'Frutilla'],
      stages: ['Siembra', 'Trasplante', 'Crecimiento', 'Cosecha'],
      custom_fields: [
        { key: 'cantidad_plantas', label: 'Cantidad de plantas',     type: 'number', unit: 'unid.',  stage: 'Siembra' },
        { key: 'ph_solucion',      label: 'pH solución',             type: 'number', unit: 'pH',     stage: 'Trasplante',  min_value: 5.5, max_value: 6.5, compliance_ref: 'Referencia técnica' },
        { key: 'ce',               label: 'Conductividad eléctrica', type: 'number', unit: 'mS/cm',  stage: 'Crecimiento', min_value: 1.5, max_value: 3.5, compliance_ref: 'Referencia técnica' },
        { key: 'temp_agua',        label: 'Temperatura del agua',    type: 'number', unit: '°C',     stage: 'Crecimiento', min_value: 18,  max_value: 24,  compliance_ref: 'Referencia técnica' },
        { key: 'dias_ciclo',       label: 'Días del ciclo',          type: 'number', unit: 'd',      stage: 'Cosecha' },
        { key: 'kg_cosechados',    label: 'Kg cosechados',           type: 'number', unit: 'kg',     stage: 'Cosecha' },
      ],
    },
    suggestedInventory: [
      { name: 'Solución nutritiva A', unit: 'L', category: 'insumo', min_stock: 20 },
      { name: 'Solución nutritiva B', unit: 'L', category: 'insumo', min_stock: 20 },
      { name: 'Semillas de lechuga', unit: 'sobre', category: 'materia_prima', min_stock: 10 },
      { name: 'Sustrato lana de roca', unit: 'm²', category: 'insumo', min_stock: 10 },
      { name: 'Film plástico', unit: 'rollo', category: 'insumo', min_stock: 3 },
      { name: 'Bolsas para envasado', unit: 'unidad', category: 'material_empaque', min_stock: 300 },
    ],
  },

  // ─── FOOD MANUFACTURING ───────────────────────────────────────────────────
  food_manufacturing: {
    label: 'Manufactura de alimentos',
    region: 'Todo el país',
    inputLabel: 'Kg de materia prima',
    outputLabel: 'Kg / unidades producidas',
    productExamples: ['Conservas', 'Pastas', 'Panificados'],
    regulator: 'ANMAT + SENASA',
    productionStages: ['Preparación', 'Producción', 'Control calidad', 'Envasado'],
    productionFields: [
      { key: 'receta',       label: 'Receta / formulación',   type: 'text',                 stage: 'Preparación' },
      { key: 'temp_proceso', label: 'Temperatura de proceso', type: 'number', unit: '°C',   stage: 'Producción',       min_value: 60, compliance_ref: 'CAA / ANMAT — temperatura de cocción' },
      { key: 'merma',        label: 'Merma',                  type: 'number', unit: '%',    stage: 'Control calidad',  max_value: 20 },
      { key: 'unidades',     label: 'Unidades producidas',    type: 'number', unit: 'unid.', stage: 'Envasado' },
    ],
    defaultConfig: {
      input_label: 'Kg de materia prima',
      output_label: 'Kg producidos',
      product_types: [],
      stages: ['Preparación', 'Producción', 'Control calidad', 'Envasado'],
      custom_fields: [
        { key: 'receta',       label: 'Receta / formulación',   type: 'text',                  stage: 'Preparación' },
        { key: 'temp_proceso', label: 'Temperatura de proceso', type: 'number', unit: '°C',    stage: 'Producción',      min_value: 60, compliance_ref: 'CAA / ANMAT — temperatura de cocción' },
        { key: 'merma',        label: 'Merma',                  type: 'number', unit: '%',     stage: 'Control calidad', max_value: 20 },
        { key: 'unidades',     label: 'Unidades producidas',    type: 'number', unit: 'unid.', stage: 'Envasado' },
      ],
    },
    suggestedInventory: [
      { name: 'Materia prima principal', unit: 'kg', category: 'materia_prima', min_stock: 200 },
      { name: 'Envases primarios', unit: 'unidad', category: 'material_empaque', min_stock: 500 },
      { name: 'Cajas de cartón', unit: 'unidad', category: 'material_empaque', min_stock: 200 },
      { name: 'Etiquetas', unit: 'unidad', category: 'material_empaque', min_stock: 500 },
      { name: 'Film termocontraíble', unit: 'rollo', category: 'material_empaque', min_stock: 5 },
    ],
  },

  // ─── PANADERÍA ────────────────────────────────────────────────────────────
  panaderia: {
    label: 'Panadería / Pastelería',
    region: 'Todo el país',
    inputLabel: 'Kg de harina',
    outputLabel: 'Kg producidos',
    productExamples: ['Pan francés', 'Pan lactal', 'Medialunas', 'Facturas', 'Tortas'],
    regulator: 'CAA + ANMAT',
    productionStages: ['Pesado', 'Amasado', 'Fermentación', 'Horneado', 'Enfriado', 'Envasado'],
    productionFields: [
      { key: 'temp_agua',         label: 'Temperatura del agua',    type: 'number', unit: '°C',  stage: 'Amasado',      min_value: 18,  max_value: 25 },
      { key: 'tiempo_amasado',    label: 'Tiempo de amasado',       type: 'number', unit: 'min', stage: 'Amasado' },
      { key: 'temp_fermentacion', label: 'Temperatura de fermentación', type: 'number', unit: '°C', stage: 'Fermentación', min_value: 24, max_value: 28 },
      { key: 'tiempo_fermentacion', label: 'Tiempo de fermentación', type: 'number', unit: 'hs', stage: 'Fermentación' },
      { key: 'temp_horneado',     label: 'Temperatura de horneado', type: 'number', unit: '°C',  stage: 'Horneado',     min_value: 180, max_value: 250, compliance_ref: 'CAA Art. 726' },
      { key: 'tiempo_horneado',   label: 'Tiempo de horneado',      type: 'number', unit: 'min', stage: 'Horneado' },
      { key: 'temp_interna',      label: 'Temperatura interna final', type: 'number', unit: '°C', stage: 'Horneado',    min_value: 90,  compliance_ref: 'CAA — cocción completa' },
      { key: 'kg_producidos',     label: 'Kg producidos',           type: 'number', unit: 'kg',  stage: 'Envasado' },
      { key: 'merma',             label: 'Merma',                   type: 'number', unit: '%',   stage: 'Envasado',     max_value: 15 },
    ],
    defaultConfig: {
      input_label: 'Kg de harina',
      output_label: 'Kg producidos',
      product_types: ['Pan francés', 'Pan lactal', 'Medialunas', 'Facturas', 'Tortas', 'Budines'],
      stages: ['Pesado', 'Amasado', 'Fermentación', 'Horneado', 'Enfriado', 'Envasado'],
      custom_fields: [
        { key: 'temp_agua',           label: 'Temperatura del agua',       type: 'number', unit: '°C',  stage: 'Amasado',      min_value: 18, max_value: 25 },
        { key: 'tiempo_amasado',      label: 'Tiempo de amasado',          type: 'number', unit: 'min', stage: 'Amasado' },
        { key: 'temp_fermentacion',   label: 'Temperatura de fermentación', type: 'number', unit: '°C', stage: 'Fermentación', min_value: 24, max_value: 28 },
        { key: 'tiempo_fermentacion', label: 'Tiempo de fermentación',     type: 'number', unit: 'hs',  stage: 'Fermentación' },
        { key: 'temp_horneado',       label: 'Temperatura de horneado',    type: 'number', unit: '°C',  stage: 'Horneado',     min_value: 180, max_value: 250, compliance_ref: 'CAA Art. 726' },
        { key: 'tiempo_horneado',     label: 'Tiempo de horneado',         type: 'number', unit: 'min', stage: 'Horneado' },
        { key: 'temp_interna',        label: 'Temperatura interna final',  type: 'number', unit: '°C',  stage: 'Horneado',     min_value: 90, compliance_ref: 'CAA — cocción completa' },
        { key: 'kg_producidos',       label: 'Kg producidos',              type: 'number', unit: 'kg',  stage: 'Envasado' },
        { key: 'merma',               label: 'Merma',                      type: 'number', unit: '%',   stage: 'Envasado',     max_value: 15 },
      ],
    },
    suggestedInventory: [
      { name: 'Harina 000',        unit: 'kg',    category: 'materia_prima',      min_stock: 200 },
      { name: 'Harina 0000',       unit: 'kg',    category: 'materia_prima',      min_stock: 100 },
      { name: 'Levadura fresca',   unit: 'kg',    category: 'insumo',             min_stock: 5 },
      { name: 'Manteca',           unit: 'kg',    category: 'materia_prima',      min_stock: 30 },
      { name: 'Azúcar',            unit: 'kg',    category: 'materia_prima',      min_stock: 50 },
      { name: 'Sal fina',          unit: 'kg',    category: 'insumo',             min_stock: 10 },
      { name: 'Bolsas de empaque', unit: 'unidad',category: 'material_empaque',   min_stock: 500 },
    ],
  },

  // ─── ACUICULTURA ──────────────────────────────────────────────────────────
  acuicultura: {
    label: 'Acuicultura / Piscicultura',
    region: 'Patagonia · NEA · Cuyo',
    inputLabel: 'Kg de alevines',
    outputLabel: 'Kg cosechados',
    productExamples: ['Trucha', 'Salmón', 'Langostinos', 'Tilapia', 'Pejerrey'],
    regulator: 'SENASA',
    productionStages: ['Siembra', 'Crecimiento', 'Control sanitario', 'Cosecha', 'Procesado'],
    productionFields: [
      { key: 'especie',          label: 'Especie',                   type: 'text',                    stage: 'Siembra' },
      { key: 'cantidad_alevines',label: 'Cantidad de alevines',      type: 'number', unit: 'unid.',   stage: 'Siembra' },
      { key: 'densidad',         label: 'Densidad de siembra',       type: 'number', unit: 'kg/m³',   stage: 'Siembra',          max_value: 25, compliance_ref: 'SENASA — referencia productiva' },
      { key: 'temp_agua',        label: 'Temperatura del agua',      type: 'number', unit: '°C',      stage: 'Crecimiento',      min_value: 8,  max_value: 18, compliance_ref: 'Referencia técnica salmonídeos' },
      { key: 'oxigeno',          label: 'Oxígeno disuelto',          type: 'number', unit: 'mg/L',    stage: 'Crecimiento',      min_value: 6,  compliance_ref: 'SENASA — mínimo vital' },
      { key: 'ph_agua',          label: 'pH del agua',               type: 'number', unit: 'pH',      stage: 'Crecimiento',      min_value: 6.5,max_value: 8.5 },
      { key: 'conversion',       label: 'Conversión alimenticia (FCR)', type: 'number',              stage: 'Crecimiento',      min_value: 1.0,max_value: 2.0, compliance_ref: 'Referencia productiva' },
      { key: 'mortalidad',       label: 'Mortalidad',                type: 'number', unit: '%',       stage: 'Control sanitario',max_value: 5,  compliance_ref: 'SENASA — referencia productiva' },
      { key: 'peso_promedio',    label: 'Peso promedio',             type: 'number', unit: 'kg',      stage: 'Cosecha' },
      { key: 'kg_cosechados',    label: 'Kg cosechados',             type: 'number', unit: 'kg',      stage: 'Cosecha' },
      { key: 'temp_proceso',     label: 'Temperatura de proceso',    type: 'number', unit: '°C',      stage: 'Procesado',        max_value: 4,  compliance_ref: 'SENASA — cadena de frío' },
    ],
    defaultConfig: {
      input_label: 'Kg de alevines',
      output_label: 'Kg cosechados',
      product_types: ['Trucha arcoíris', 'Salmón del Atlántico', 'Langostino', 'Tilapia', 'Pejerrey'],
      stages: ['Siembra', 'Crecimiento', 'Control sanitario', 'Cosecha', 'Procesado'],
      custom_fields: [
        { key: 'especie',           label: 'Especie',                     type: 'text',                  stage: 'Siembra' },
        { key: 'cantidad_alevines', label: 'Cantidad de alevines',        type: 'number', unit: 'unid.', stage: 'Siembra' },
        { key: 'densidad',          label: 'Densidad de siembra',         type: 'number', unit: 'kg/m³', stage: 'Siembra',           max_value: 25, compliance_ref: 'SENASA — referencia productiva' },
        { key: 'temp_agua',         label: 'Temperatura del agua',        type: 'number', unit: '°C',    stage: 'Crecimiento',       min_value: 8,  max_value: 18, compliance_ref: 'Referencia técnica salmonídeos' },
        { key: 'oxigeno',           label: 'Oxígeno disuelto',            type: 'number', unit: 'mg/L',  stage: 'Crecimiento',       min_value: 6,  compliance_ref: 'SENASA — mínimo vital' },
        { key: 'ph_agua',           label: 'pH del agua',                 type: 'number', unit: 'pH',    stage: 'Crecimiento',       min_value: 6.5,max_value: 8.5 },
        { key: 'conversion',        label: 'Conversión alimenticia (FCR)', type: 'number',               stage: 'Crecimiento',       min_value: 1.0,max_value: 2.0, compliance_ref: 'Referencia productiva' },
        { key: 'mortalidad',        label: 'Mortalidad',                  type: 'number', unit: '%',     stage: 'Control sanitario', max_value: 5,  compliance_ref: 'SENASA — referencia productiva' },
        { key: 'peso_promedio',     label: 'Peso promedio',               type: 'number', unit: 'kg',    stage: 'Cosecha' },
        { key: 'kg_cosechados',     label: 'Kg cosechados',               type: 'number', unit: 'kg',    stage: 'Cosecha' },
        { key: 'temp_proceso',      label: 'Temperatura de proceso',      type: 'number', unit: '°C',    stage: 'Procesado',         max_value: 4,  compliance_ref: 'SENASA — cadena de frío' },
      ],
    },
    suggestedInventory: [
      { name: 'Alimento balanceado trucha', unit: 'kg',    category: 'materia_prima', min_stock: 500 },
      { name: 'Oxígeno líquido',            unit: 'L',     category: 'insumo',        min_stock: 100 },
      { name: 'Red cosecha',                unit: 'unidad',category: 'insumo',        min_stock: 2 },
      { name: 'Antibióticos autorizados',   unit: 'L',     category: 'insumo',        min_stock: 5 },
      { name: 'Cajas de telgopor',          unit: 'unidad',category: 'material_empaque', min_stock: 200 },
      { name: 'Hielo en escama',            unit: 'kg',    category: 'insumo',        min_stock: 200 },
    ],
  },

  // ─── COSMÉTICA ────────────────────────────────────────────────────────────
  cosmetica: {
    label: 'Cosmética / Dermocosméticos',
    region: 'Todo el país',
    inputLabel: 'Kg de materias primas',
    outputLabel: 'Unidades producidas',
    productExamples: ['Cremas', 'Lociones', 'Champú', 'Jabones artesanales', 'Protectores solares'],
    regulator: 'ANMAT',
    productionStages: ['Formulación', 'Mezclado', 'Control de calidad', 'Envasado', 'Liberación'],
    productionFields: [
      { key: 'formula',           label: 'Código de fórmula',          type: 'text',                    stage: 'Formulación' },
      { key: 'lote_mp',           label: 'Lote de materia prima',      type: 'text',                    stage: 'Formulación' },
      { key: 'temp_proceso',      label: 'Temperatura de proceso',     type: 'number', unit: '°C',      stage: 'Mezclado',           compliance_ref: 'Referencia técnica por fórmula' },
      { key: 'tiempo_mezclado',   label: 'Tiempo de mezclado',         type: 'number', unit: 'min',     stage: 'Mezclado' },
      { key: 'ph_producto',       label: 'pH del producto',            type: 'number', unit: 'pH',      stage: 'Control de calidad', min_value: 4.5, max_value: 8.5, compliance_ref: 'ANMAT Disp. 4622/12' },
      { key: 'resultado_micro',   label: 'Resultado microbiológico',   type: 'select', options: ['Conforme', 'No conforme', 'Pendiente'], stage: 'Control de calidad', compliance_ref: 'ANMAT Disp. 4622/12' },
      { key: 'unidades_envasadas',label: 'Unidades envasadas',         type: 'number', unit: 'unid.',   stage: 'Envasado' },
      { key: 'numero_liberacion', label: 'N° de liberación ANMAT',     type: 'text',                    stage: 'Liberación' },
    ],
    defaultConfig: {
      input_label: 'Kg de materias primas',
      output_label: 'Unidades producidas',
      product_types: ['Cremas hidratantes', 'Lociones corporales', 'Champú', 'Jabones', 'Protector solar', 'Sérum'],
      stages: ['Formulación', 'Mezclado', 'Control de calidad', 'Envasado', 'Liberación'],
      custom_fields: [
        { key: 'formula',            label: 'Código de fórmula',         type: 'text',                    stage: 'Formulación' },
        { key: 'lote_mp',            label: 'Lote de materia prima',     type: 'text',                    stage: 'Formulación' },
        { key: 'temp_proceso',       label: 'Temperatura de proceso',    type: 'number', unit: '°C',      stage: 'Mezclado',           compliance_ref: 'Referencia técnica por fórmula' },
        { key: 'tiempo_mezclado',    label: 'Tiempo de mezclado',        type: 'number', unit: 'min',     stage: 'Mezclado' },
        { key: 'ph_producto',        label: 'pH del producto',           type: 'number', unit: 'pH',      stage: 'Control de calidad', min_value: 4.5, max_value: 8.5, compliance_ref: 'ANMAT Disp. 4622/12' },
        { key: 'resultado_micro',    label: 'Resultado microbiológico',  type: 'select', options: ['Conforme', 'No conforme', 'Pendiente'], stage: 'Control de calidad', compliance_ref: 'ANMAT Disp. 4622/12' },
        { key: 'unidades_envasadas', label: 'Unidades envasadas',        type: 'number', unit: 'unid.',   stage: 'Envasado' },
        { key: 'numero_liberacion',  label: 'N° de liberación ANMAT',   type: 'text',                    stage: 'Liberación' },
      ],
    },
    suggestedInventory: [
      { name: 'Aceite de argán',        unit: 'L',     category: 'materia_prima',    min_stock: 10 },
      { name: 'Manteca de karité',      unit: 'kg',    category: 'materia_prima',    min_stock: 10 },
      { name: 'Conservantes (Phenonip)',unit: 'kg',    category: 'insumo',           min_stock: 2 },
      { name: 'Fragancias',             unit: 'L',     category: 'insumo',           min_stock: 5 },
      { name: 'Frascos 200mL',          unit: 'unidad',category: 'material_empaque', min_stock: 500 },
      { name: 'Tapas y dosificadores',  unit: 'unidad',category: 'material_empaque', min_stock: 500 },
      { name: 'Etiquetas',              unit: 'unidad',category: 'material_empaque', min_stock: 1000 },
    ],
  },

  // ─── PESCA ────────────────────────────────────────────────────────────────
  pesca: {
    label: 'Pesca / Mariscos',
    region: 'Patagonia · Litoral atlántico',
    inputLabel: 'Kg recibidos',
    outputLabel: 'Kg envasados',
    productExamples: ['Merluza', 'Calamar', 'Langostino', 'Vieira', 'Mejillón'],
    regulator: 'SENASA + SAGyP',
    productionStages: ['Recepción', 'Clasificación', 'Procesado', 'Congelado', 'Envasado', 'Despacho'],
    productionFields: [
      { key: 'especie',              label: 'Especie',                   type: 'text',                      stage: 'Recepción' },
      { key: 'origen',               label: 'Origen / embarcación',      type: 'text',                      stage: 'Recepción' },
      { key: 'temp_recepcion',       label: 'Temperatura de recepción',  type: 'number', unit: '°C',        stage: 'Recepción',    max_value: 4,    compliance_ref: 'SENASA — cadena de frío' },
      { key: 'kg_recibidos',         label: 'Kg recibidos',              type: 'number', unit: 'kg',        stage: 'Recepción' },
      { key: 'categoria',            label: 'Categoría / talla',         type: 'text',                      stage: 'Clasificación' },
      { key: 'merma_clasificacion',  label: 'Merma de clasificación',    type: 'number', unit: '%',         stage: 'Clasificación',max_value: 15 },
      { key: 'temp_proceso',         label: 'Temperatura de proceso',    type: 'number', unit: '°C',        stage: 'Procesado',    max_value: 7,    compliance_ref: 'SENASA Res. 4238' },
      { key: 'rendimiento',          label: 'Rendimiento de proceso',    type: 'number', unit: '%',         stage: 'Procesado',    min_value: 40, max_value: 70 },
      { key: 'temp_congelado',       label: 'Temperatura de congelado',  type: 'number', unit: '°C',        stage: 'Congelado',    max_value: -18,  compliance_ref: 'SENASA — congelado IQF' },
      { key: 'kg_envasados',         label: 'Kg envasados',              type: 'number', unit: 'kg',        stage: 'Envasado' },
      { key: 'destino',              label: 'Destino',                   type: 'select', options: ['Exportación', 'Mercado interno', 'Industria'], stage: 'Despacho' },
    ],
    defaultConfig: {
      input_label: 'Kg recibidos',
      output_label: 'Kg envasados',
      product_types: ['Merluza filete', 'Calamar entero', 'Langostino pelado', 'Vieira', 'Mejillón'],
      stages: ['Recepción', 'Clasificación', 'Procesado', 'Congelado', 'Envasado', 'Despacho'],
      custom_fields: [
        { key: 'especie',             label: 'Especie',                   type: 'text',                      stage: 'Recepción' },
        { key: 'origen',              label: 'Origen / embarcación',      type: 'text',                      stage: 'Recepción' },
        { key: 'temp_recepcion',      label: 'Temperatura de recepción',  type: 'number', unit: '°C',        stage: 'Recepción',     max_value: 4,   compliance_ref: 'SENASA — cadena de frío' },
        { key: 'kg_recibidos',        label: 'Kg recibidos',              type: 'number', unit: 'kg',        stage: 'Recepción' },
        { key: 'categoria',           label: 'Categoría / talla',         type: 'text',                      stage: 'Clasificación' },
        { key: 'merma_clasificacion', label: 'Merma de clasificación',    type: 'number', unit: '%',         stage: 'Clasificación', max_value: 15 },
        { key: 'temp_proceso',        label: 'Temperatura de proceso',    type: 'number', unit: '°C',        stage: 'Procesado',     max_value: 7,   compliance_ref: 'SENASA Res. 4238' },
        { key: 'rendimiento',         label: 'Rendimiento de proceso',    type: 'number', unit: '%',         stage: 'Procesado',     min_value: 40, max_value: 70 },
        { key: 'temp_congelado',      label: 'Temperatura de congelado',  type: 'number', unit: '°C',        stage: 'Congelado',     max_value: -18, compliance_ref: 'SENASA — congelado IQF' },
        { key: 'kg_envasados',        label: 'Kg envasados',              type: 'number', unit: 'kg',        stage: 'Envasado' },
        { key: 'destino',             label: 'Destino',                   type: 'select', options: ['Exportación', 'Mercado interno', 'Industria'], stage: 'Despacho' },
      ],
    },
    suggestedInventory: [
      { name: 'Cajas de cartón',         unit: 'unidad', category: 'material_empaque', min_stock: 500 },
      { name: 'Bolsas criogénicas',      unit: 'unidad', category: 'material_empaque', min_stock: 1000 },
      { name: 'Hielo en escama',         unit: 'kg',     category: 'insumo',           min_stock: 500 },
      { name: 'Etiquetas exportación',   unit: 'unidad', category: 'material_empaque', min_stock: 1000 },
      { name: 'Guantes de procesado',    unit: 'par',    category: 'insumo',           min_stock: 100 },
      { name: 'Termómetros de control',  unit: 'unidad', category: 'insumo',           min_stock: 3 },
    ],
  },
}

export const INDUSTRY_LIST = Object.entries(INDUSTRIES).map(([value, meta]) => ({
  value: value as Industry,
  label: meta.label,
  region: meta.region,
  regulator: meta.regulator,
}))

export const INDUSTRY_GROUPS = [
  {
    label: 'Agroindustria',
    items: ['tambo', 'dairy', 'ganaderia', 'frigorifico', 'apicultura', 'avicultura', 'chacinados'] as Industry[],
  },
  {
    label: 'Bebidas y vinos',
    items: ['bodega', 'cerveceria', 'olivicultura'] as Industry[],
  },
  {
    label: 'Campo y cultivos',
    items: ['agro_campo', 'cerealera', 'fruticultura', 'yerbatera', 'hidroponia'] as Industry[],
  },
  {
    label: 'Mar y agua',
    items: ['acuicultura', 'pesca'] as Industry[],
  },
  {
    label: 'Manufactura y otros',
    items: ['food_manufacturing', 'panaderia', 'cosmetica'] as Industry[],
  },
]
